src/Entity/FollowNotification.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FollowNotificationRepository")
 */
class FollowNotification extends Notifications
{

    /**
     * @ORM\ManyToOne("App\Entity\User")
     */
    private $followed_by;

    /**
     * @return mixed
     */
    public function getFollowedBy()
    {
        return $this->followed_by;
    }

    /**
     * @param mixed $followed_by
     */
    public function setFollowedBy($followed_by): void
    {
        $this->followed_by = $followed_by;
    }



}

src/Entity/Notifications.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NotificationsRepository")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"like" = "LikeNotification","follow" = "FollowNotification"})
 */
abstract class Notifications
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne("App\Entity\User")
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $seen;

    public function __construct ()
    {

        $this->seen = false;

    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getSeen()
    {
        return $this->seen;
    }

    /**
     * @param mixed $seen
     */
    public function setSeen($seen): void
    {
        $this->seen = $seen;
    }

    public function getId()
    {
        return $this->id;
    }
}

src/Controller/NotificationController.php
<?php

namespace App\Controller;

use App\Entity\Notifications;
use App\Repository\NotificationsRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Security("is_granted('ROLE_USER')")
 * @Route("/notification")
 */
class NotificationController extends Controller
{
    /**
     * @var NotificationsRepository
     */
    public $notificationsRepository;

    public function __construct (NotificationsRepository $notificationsRepository)
    {
        $this->notificationsRepository = $notificationsRepository;
    }

    /**
     * @Route("/all",name="all_notifications")
     */
    public function index ()
    {

        return $this->render("notification/notifications.html.twig",[
            "notifications" => $this->notificationsRepository->findBy([
                "user"  => $this->getUser(),
                "seen"  => false,
            ])
        ]);

    }

    /**
     * @Route("/unread-count",name="notification_unread")
     */
    public function unreadCount ()
    {
    
        return new JsonResponse([
           "count"  => $this->notificationsRepository->findUnseenByUser($this->getUser())
        ]);
    
    }

    /**
     * @Route("/acknowledge/{id}",name="notification_acknowledge")
     */
    public function acknowledge (Notifications $notifications)
    {
    
        $notifications->setSeen(True);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute("all_notifications");
    
    }

}

templates/notification/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'src/Controller/NotificationController.php'|file_link(0) }}">src/Controller/NotificationController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'templates/notification/index.html.twig'|file_link(0) }}">templates/notification/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/notification/notifications.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="card">
        <div class="card-body">
            <h5>Unread Notifications</h5>
        </div>
        <ul class="list-group list-group-flush">
            {% for notification in notifications %}

                <li class="list-group-item">

                    {% if notification is like %}

                        <a href="{{ path('micro_post_by_user',{'username': notification.likedBy.username}) }}">
                            {{ notification.likedBy.username }}</a>
                        liked your
                        <a href="{{ path('micro_post_post',{'id':notification.microPost.id}) }}">post</a>

                        <a href="{{ path('notification_acknowledge',{'id':notification.id}) }}">OK</a>

                     {% elseif notification is follow %}

                         <a href="{{ path('micro_post_by_user',{'username': notification.followedBy.username}) }}">
                             {{ notification.followedBy.username }}</a>
                         Started following you

                         <a href="{{ path('notification_acknowledge',{'id':notification.id}) }}">OK</a>


                    {% endif %}


                </li>

            {% endfor %}
        </ul>
    </div>
{% endblock %}